// <auto-generated />
using System;
using ApiFury.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFury.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiFury.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Server");

                    b.Property<string>("Username");

                    b.Property<string>("token");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiFury.Models.MyVillages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdVillage");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MyVillages");
                });

            modelBuilder.Entity("ApiFury.Models.Villages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("ArgX");

                    b.Property<short>("ArgY");

                    b.Property<bool>("IsEmpty");

                    b.Property<string>("Name");

                    b.Property<string>("PlayerName");

                    b.Property<short>("Population");

                    b.Property<int?>("UserId");

                    b.Property<long>("Villageid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("ApiFury.Models.MyVillages", b =>
                {
                    b.HasOne("ApiFury.Entities.User")
                        .WithMany("MyVillages")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ApiFury.Models.Villages", b =>
                {
                    b.HasOne("ApiFury.Entities.User")
                        .WithMany("Villages")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
